### ISSUE TITLE
Ban doesnt work

### ISSUE THREAD

**Issue by zirekx** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#10] opened 2020-12-08 17:17 UTC
When I use banAll bot first tries to ban himself then crash.
https://cdn.discordapp.com/attachments/699876521086812292/785917937290575902/unknown.png

**Comment by zirekx** [comment] 2020-12-08 17:29
And the same happens when I try to kick all.

**Comment by TKperson** [comment] 2020-12-08 17:45
Can you take a full screenshot of all the errors? 
Try run it with cmd to see all the errors when it crash.

**Comment by zirekx** [comment] 2020-12-08 17:47
![image](https://user-images.githubusercontent.com/75585280/101521250-dca27500-3985-11eb-9110-a19a42fe3345.png)

**Comment by TKperson** [comment] 2020-12-08 17:56
The bot won't be able to ban itself (if it failed to ban a person it will skip that user), so you don't have to worry about this (But I'll fix this in c-realV2)
If you are using one of the "all" (like kickAll, banAll) command, it might be an caused by the intents (intents allows the bot to see the full list of members in the server. If the bot can't see the full list, then it won't be able to ban everyone) feature that discord added, and this will be fixed in c-realV2

**Comment by TKperson** [comment] 2020-12-22 20:19
fixed for normal bot versions in V2, but for selfbots I need to find another way

**Closed by TKperson** 2020-12-22 20:19 UTC
Labels: bug
