### ISSUE TITLE
Why is str happening?

### ISSUE THREAD

**Issue by rockdude129** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#29] opened 2021-02-27 05:08 UTC
<img width="459" alt="Screen Shot 2021-02-26 at 9 08 45 PM" src="https://user-images.githubusercontent.com/79297356/109376073-d16d3000-7876-11eb-8f31-b902102f5570.png">

**Comment by TKperson** [comment] 2021-02-27 05:14
I tried this command on my compute, with the same script. 

I'm guessing there might be something wrong on your side of script? It might be caused by anti virus (if you have one)

If you restarted the bot and it's still showing you the same error, then you should make a bug report and tell me the steps you have done to get that error.

**Comment by cyxl** [comment] 2021-03-02 17:35
If @rockdude129 doesn't respond in 3 days I am closing this issue.

**Comment by rockdude129** [comment] 2021-03-02 19:10
Yea I restarted, maybe update your code if you changed it just to be sure. Well I am on mac, using vs code and I copied the code in and stuff. Please try updating the code so I can see if it works.

**Comment by TKperson** [comment] 2021-03-03 03:52
Hmm I don't have a Mac computer, but I will not be able to fix this(bug) if I can't reproduce the bug.

**Comment by rockdude129** [comment] 2021-03-04 03:35
Oh ok. Can you try using like a mac vm?

**Comment by cyxl** [comment] 2021-03-04 03:36
@rockdude129  Mac dosnt distribute there os sorry we cant

**Comment by rockdude129** [comment] 2021-03-04 03:37
Oh ok

**Comment by TKperson** [comment] 2021-03-04 09:34
There are Mac OS iso images. I'm not going to say I have it in here (probably illegal). It's going to run at 5 FPS on my computer.

**Closed** 2021-03-10 16:46 UTC
